### ISSUE TITLE
Mouse3D vs Joy3D

### ISSUE THREAD

**Issue by dzervas** [arpruss/mouse3d_stm32f1#3]
@arpruss can you please explain the difference between Mouse3D and Joy3D? is it just a delta vs absolute values?

Thank you for your work, you seem to be the only one that emulates a spacemouse with proper HID

**Comment by arpruss** [comment]
Joy3D emulates a multiaxis joystick. Mouse3D emulates a 3D connexion spacemouse, which is close to a multiaxis joystick, but not quite the same (e.g., it doesn't declare the controller as a joystick, but as a "multiaxis controller"). It's a use-case issue. If you want to use a SpaceMouse 4000 with a game like Descent, the joystick mode might be a bit more compatible, while if you want to use it with drivers for a 3D connexion spacemouse, you should use it in Mouse3D mode.

**Comment by dzervas** [comment]
I've never used a spacemouse but my understanding is that "you have a 3 axis joystick that can move the part" and joystick makes more sense (delta) vs the mouse

Maybe that's not how spacemouse works in CAD?

**Comment by arpruss** [comment]
The spacemouse is physically a 3-axis analog joystick where you can additionally twist the stick (actually, a ball or a knob) around the three axes. A typical use-case is that pushing the joystick moves the part in that direction, and twisting rotates the part. It is incremental like a joystick. You push or twist harder, and it moves or rotates faster.

"Mouse" is a misnomer, in terms of user experience, physical construction or HID report (which is a modification of a joystick report).

My project is for taking an old pre-USB SpaceBall 4000/5000, and interfacing it via USB either as a joystick or as a modern SpaceMouse (where it will work with modern 3DConnexion drivers).
